### ISSUE TITLE
Performance issues on large data sets

### ISSUE THREAD

**Issue by Luc1412** [peterhanania/Discord-Package#12]
I got a 2016 Mac Pro with an older i5 16GB RAM running latest stable MacOS. I tested it with latest stable Safari and Brave.

When dragging and dropping the package it got stuck while loading the messages. On Safari it first told me to close the site due to high load. Afterwards it reloaded the page forcefully. On Brave it closed the site and showed an error page while loading messages.

It seems like the parsing/loading is very inefficient especially when having huge data sets and could be optimized.

**Comment by Luc1412** [comment]
Also running this on my high end Windows machine with brave, it crash. 
![image](https://user-images.githubusercontent.com/24532065/185798848-021bdbb3-66b1-4424-a418-513570b2375e.png)

**Comment by peterhanania** [comment]
Hey, we are aware of that as we are working on optimizing the way we extract data.

We are sorry that you are experiencing issues with our website.

The site now is very laggy sometimes when there’s a lot of data.
