### ISSUE TITLE
Wrong amount spent on Discord

### ISSUE THREAD

**Issue by Yan-Jobs** [peterhanania/Discord-Package#13]
Hi! First of all, congrats you did an amazinngggggg work, the UI looks nice and you added more data views etc.. Only problem when you purchase gifts with Apple, it doesn't show up in my summary. I looked into my account.json and they are listed in it. Also it shows up in my "gift codes" section (e.g.: You created 137 gift codes (real data here xD)). So I thought it could be cool that you add this data in the summary.
Have a nice day :)
- Yan

**Comment by peterhanania** [comment]
Hey! Thanks for the feedback. Could you join the discord at discordpackage.com/discord and tell me more about how your gifts didn’t show so that I add/fix that? Thanks!
