### ISSUE TITLE
Despite not having a Verified Bot, I have a badge on the site telling me I do.

### ISSUE THREAD

**Issue by auxtinn** [peterhanania/Discord-Package#134]
Re: https://github.com/peterhanania/Discord-Package/blob/067d3b1a4902d5185b59436acb130480d9797c25/components/json/badges/index.json#L87

I do not have any verified bots, but am given this badge on the site telling me I do.

**Comment by Lulalaby** [comment]
That whole line is out of place + it claims to be documented but it def isn't.
It might be incorrect data

**Comment by Lulalaby** [comment]
This is fixed and can be close @peterhanania
