### ISSUE TITLE
fix the responsiveness.

### ISSUE THREAD

**Issue by kunaaal13** [peterhanania/Discord-Package#16]
The website doesn't look responsive at the mobile device, i'd love to fix that responsiveness.

**Comment by peterhanania** [comment]
Hello can you elaborate? Can you be more detailed? Any picture?

**Comment by kunaaal13** [comment]
Everything is going in the left and not taking the full width of the screen.

![Screenshot_2022-10-05-06-38-05-98_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://user-images.githubusercontent.com/84015751/193958293-890d8ec9-c6ee-49c4-8b00-0aca7e2a799e.jpg)

**Comment by peterhanania** [comment]
Seems like the new update messed up mobile, I’ll fix it soon.

**Comment by peterhanania** [comment]
fixed in https://github.com/peterhanania/Discord-Package/commit/01d5bb7d42900d163bded3d8cc77bce0d1c64f3a
