### ISSUE TITLE
"Out of Memory" error when clicking "Favorite Words" button.

### ISSUE THREAD

**Issue by Taureon** [peterhanania/Discord-Package#18]
![image](https://user-images.githubusercontent.com/45183108/196243398-c37c0af9-9b06-4777-b26e-604b6bc4daf2.png)
If you click the heart-shaped button, the app freezes for some seconds and then this happens:
![image](https://user-images.githubusercontent.com/45183108/196243553-c1446795-aa0e-4044-bdcd-2b22991b2e82.png)

**Comment by peterhanania** [comment]
Please join the discord at discordpackage.com/discord and report it there ;)

**Comment by Taureon** [comment]
seems inefficient, but okay 👍
