### ISSUE TITLE
Any way to host this privately on Replit?

### ISSUE THREAD

**Issue by BubbleBubblePlayz** [peterhanania/Discord-Package#19]
I wanted to host it myself and the only thing I know that works for completely online hosting is using [Replit](https://replit.com/~). Any tips?

**Comment by peterhanania** [comment]
Hello, you can click the button on the readme to deploy to Vercel easily but if you want replit you can find the node js installation guide at the bottom.

When creating the repl select to import from github put the github link and then when it asks for the start command use ‘npm run dev’

Run and that’s it!
