### ISSUE TITLE
Displaying wrong # of messages in yearly view

### ISSUE THREAD

**Issue by rudnam** [peterhanania/Discord-Package#25]
![image](https://user-images.githubusercontent.com/70255485/198037278-9306114a-2c06-4aaf-8b69-f29959ebff6e.png)
![image](https://user-images.githubusercontent.com/70255485/198037317-c4e28562-de2e-4dea-b81d-2466400143b9.png)
Have more than a hundred messages on a single channel
![image](https://user-images.githubusercontent.com/70255485/198037336-bf492e1f-4b7c-4999-a208-531ef1ed44fb.png)

**Comment by LittleDyingDuck** [comment]
could depend on when u requested ur data package, the data is always gonna be a few weeks out of date because of the time it takes for discord to collect

**Comment by rudnam** [comment]
They're on my data package though, the first two photos are from my data package

**Comment by peterhanania** [comment]
I haven't figured out the issue from yearly messages not being shown properly. I will try to find a fix in the next update

**Comment by peterhanania** [comment]
I'm trying to debug the issue, my dates seem perfect. Waiting for someone to trust me with their data package, or a contributor that has their graphs messed up so that they can try and see what's causing the issue.

If you know how to code by any chance please leave me a message on my discord: Peter_#4444. I can tell you how to debug it so that we can together find the root cause of this issue.

**Comment by farkon00** [comment]
I have that bug with my package, gonna try finding the cause later.
![image](https://user-images.githubusercontent.com/59134591/198892543-369d25bc-3e02-4fa5-b31a-aec6e508e963.png)

**Comment by peterhanania** [comment]
@farkon00 would be great 😄 thanks

**Comment by farkon00** [comment]
For now i can only say, that it doesn't count missing messages in the graph to global count too. But at the same time has message count for channels from guilds, that i only joined in 2022.

**Comment by peterhanania** [comment]
Every message has a unique timestamp. Discord package loops through all timestamps and creates an array of years.
Then for each year discord package adds the message count for each year. You will have to play with the code to know what is causing the issue.
