### ISSUE TITLE
The yearly messages view is displaying in the wrong order

### ISSUE THREAD

**Issue by Dhoru** [peterhanania/Discord-Package#27]
so if my messages are shown from 2018 to 2022:
2022's messages are shown in 2018
2021's in 2019
2020's in 2020
2019's in 2021
2018's in 2020

This makes the graph become shown right-to-left, but the years left-to-right

**Comment by farkon00** [comment]
You meant 2022's message in 2018?

**Comment by Dhoru** [comment]
> You meant 2022's message in 2018?

yes

**Comment by Dhoru** [comment]
basically it shows like this: 
![image](https://user-images.githubusercontent.com/70144216/200122572-190c2cbb-3354-4c2a-a45f-443fad35fdf1.png)

even though it should look like this:
![image](https://user-images.githubusercontent.com/70144216/200122605-f78fe062-731c-4aaa-a02b-a8032a70d679.png)

**Comment by peterhanania** [comment]
I will look into this more, thank you for really finding this out. Can you send me a fr on Discord: Peter_#4444 and we could sort this out together.

**Comment by Dhoru** [comment]
all right
