### ISSUE TITLE
Friend requests rejected text has a typo

### ISSUE THREAD

**Issue by maxwellward** [peterhanania/Discord-Package#30]
![image](https://user-images.githubusercontent.com/13861522/200983413-4e1b8199-9d7f-45f4-89ff-16781365e8a3.png)

The "have" needs to be removed to be grammatically correct.

**Comment by fr0nt-2-b4ck** [comment]
Hi Peter,
Just to provide a minor update to the issue on here, as we discussed on the Discord - I've begun working on this .
AthruZ

**Comment by peterhanania** [comment]
Fixed in #125
