### ISSUE TITLE
Currency symbol is always on the left

### ISSUE THREAD

**Issue by maxwellward** [peterhanania/Discord-Package#34]
Some countries put the currency symbol on the left, some put it on the right. We should add a field in currencies.json that indicates whether it should be on the left or right, and conditionally render it based on that.

In doing this, we should also extract the logic from the component to a helper function that can be passed a value and will return the correctly formatted amount + currency symbol.

**Comment by maxwellward** [comment]
To whoever works on this: 

The currencies.json objects can be changed to add one extra field, "side", or whatever name would be best. For example:
```
{
    "currency": "Canada Dollar",
    "abbreviation": "CAD",
    "symbol": "$",
    "side": "left"
  },
```

A helper function can then be made in `index.js` (I will make an issue for extracting helper functions later, for now just put them there) that accepts one value, "amount". The function can then do the following:

1. Get the most used currency
2. Get the symbol for said currency
3. Decide which side the symbol should go on
4. Piece together a final string (ex. $100.32, or 124.56 zł)
5. Return the string to the component and render it

As I'm marking this as an issue for beginners, and as such, I want to remind anyone who takes it that you can reach out if you have any questions, no matter how simple :)

**Comment by michaela559** [comment]
Hello, can I try this?

**Comment by maxwellward** [comment]
> Hello, can I try this? 

Sure! Go for it. Let me know if you have any questions.

**Comment by michaela559** [comment]
sorry, can you explain what you mean by get the most used currency and where to return it/render it?

**Comment by peterhanania** [comment]
The current code already renders the most used currency. You just have to make it that some symbols are placed on the left and some on the right. This can be done by adding “side” to each currency which can be left or right and to make the frontend know what to place right or left.

**Comment by peterhanania** [comment]
To add, the JSON can be found here: /components/json/other/currencies.json. So the first step is to add “side” to each that represents if the symbol should be on the left or right. Next is to make the frontend read this property and show the symbol based on it.

**Comment by michaela559** [comment]
yes, i have the side part. I was only confused if I have to work with the uploaded data, like get the most used currency from it, and how to work with it. So if the only value the helper function accepts is the amount, then how do i know about the currency

**Comment by peterhanania** [comment]
I recommend you fake the data (edit it yourself) to test. But that won’t be needed till later. Just complete the first step and I can tell you what to do next !

**Comment by michaela559** [comment]
one more thing, wehre can i call the helper function?

**Comment by michaela559** [comment]
Okay I created a function getSymbol(amount, mostUsedCurrency) that returns a string like "$50". Is it okay that way?

**Comment by peterhanania** [comment]
As long as the symbols that should be on the left are on the left and the right on the right then that’s okay

**Comment by farkon00** [comment]
@michaela559 Hey, that seems like you solved the issue in your commit. If it's ready can you please create pull request, so your changes can be merged into main branch. Thanks.

**Comment by peterhanania** [comment]
Fixed in latest commit.
