### ISSUE TITLE
Add support for new discord badge and other flags

### ISSUE THREAD

**Issue by peterhanania** [peterhanania/Discord-Package#39]
This issue uses the PR done by @Lulalaby (https://github.com/peterhanania/Discord-Package/pull/36) to add corresponding badge (svg icon) to each new flag.

**Comment by Lulalaby** [comment]
![26c7a60fb1654315e0be26107bd47470](https://user-images.githubusercontent.com/14029133/201426162-bbf22e90-81ad-4f7b-88bd-a8cca832b83d.svg)
Active Developer Badge (SVG)
Source: https://discord.com/assets/26c7a60fb1654315e0be26107bd47470.svg

**Comment by peterhanania** [comment]
Done in #44
